"""Precompute blank-out keywords for each passage with spaCy's neural tagger.

The browser app blanks words for the "Fill the blanks" review mode. Rather than
hand-maintaining verb/noun word lists, we run each (static) passage through
spaCy's neural POS tagger once, offline, and emit a data file the app reads.

For every passage we mark the *content* words -- proper nouns, nouns, verbs,
adjectives, and meaningful adverbs -- and rank them by importance. Indices are
aligned to `text.split(" ")` so they line up exactly with the app's tokens.

Output: keywords.js -> `export const keywordIndices = { <id>: [idx, ...] }`
where each list is ordered most-important first. The app applies its own
spacing / density cap on top.
"""
import json
import re
import sys
from pathlib import Path

import spacy

ROOT = Path(__file__).resolve().parent.parent
PASSAGES_JS = ROOT / "data" / "passages.js"
OUT_JS = ROOT / "data" / "keywords.js"

# POS tags worth blanking, with an importance weight. AUX (is/are/will/have as
# helper), DET, ADP, PRON, CCONJ, SCONJ, PART, etc. are deliberately excluded.
POS_WEIGHT = {"PROPN": 5.0, "NOUN": 4.0, "VERB": 4.0, "ADJ": 2.6, "ADV": 2.0, "NUM": 1.5}


def load_passages():
    src = PASSAGES_JS.read_text(encoding="utf-8")
    start = src.index("[")
    end = src.rindex("]") + 1
    return json.loads(src[start:end])


def word_spans(text):
    """Char spans for text.split(' ') tokens, matching the app's indexing."""
    spans, pos = [], 0
    for w in text.split(" "):
        spans.append((pos, pos + len(w)))
        pos += len(w) + 1
    return spans


def keywords_for(nlp, text):
    words = text.split(" ")
    spans = word_spans(text)
    best = {}  # word index -> weight
    doc = nlp(text)
    for tok in doc:
        w = POS_WEIGHT.get(tok.pos_)
        if w is None:
            continue
        # spaCy flags common content verbs (keep, make, give, take...) as stop
        # words; those are meaningful here, so only let is_stop veto the lighter
        # adjective/adverb/number tags (own, such, very, many...).
        if tok.is_stop and tok.pos_ not in ("PROPN", "NOUN", "VERB"):
            continue
        if not re.search(r"[A-Za-z]", tok.text):
            continue
        # map this spaCy token to the whitespace-split word that contains it
        wi = None
        for i, (s, e) in enumerate(spans):
            if s <= tok.idx < e or (s <= tok.idx and tok.idx < e + 1 and tok.idx < e):
                wi = i
                break
        if wi is None:
            # fall back to nearest span start
            wi = min(range(len(spans)), key=lambda i: abs(spans[i][0] - tok.idx))
        score = w + min(len(re.sub(r"[^A-Za-z']", "", words[wi])), 9) * 0.1
        if score > best.get(wi, 0):
            best[wi] = score
    return [i for i, _ in sorted(best.items(), key=lambda kv: (-kv[1], kv[0]))]


def main():
    nlp = spacy.load("en_core_web_sm")
    passages = load_passages()
    out = {}
    tot_words = tot_marked = 0
    for p in passages:
        idx = keywords_for(nlp, p["text"])
        out[p["id"]] = idx
        tot_words += len(p["text"].split(" "))
        tot_marked += len(idx)
    body = ",\n".join(f'  "{pid}": {json.dumps(idx)}' for pid, idx in out.items())
    OUT_JS.write_text(
        "/* Auto-generated by tools/gen_keywords.py using spaCy (en_core_web_sm).\n"
        "   Per-passage content-word indices (aligned to text.split(' ')), ordered\n"
        "   most-important first. Do not edit by hand -- re-run the generator. */\n"
        "export const keywordIndices = {\n" + body + "\n};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT_JS.name}: {len(passages)} passages, "
          f"{tot_marked} content words tagged across {tot_words} words "
          f"({100*tot_marked/tot_words:.1f}% eligible).")


if __name__ == "__main__":
    sys.exit(main())
